--------------------------------------------------------
-- CUREWELL HOSPITAL MANAGEMENT SYSTEM (HMS)
-- MASTER DATABASE SCHEMA & SEED SCRIPT FOR ORACLE CLOUD
-- Target: Oracle Autonomous Database (Always Free / Cloud)
-- Standard: 3NF Relational Architecture & Cloud-Optimized
--------------------------------------------------------

-- =====================================================
-- SECTION 1: ENVIRONMENT & CLEANUP
-- =====================================================

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

-- Drop all existing views safely
BEGIN
   FOR cur_rec IN (SELECT view_name FROM user_views WHERE view_name LIKE 'V_%') LOOP
      EXECUTE IMMEDIATE 'DROP VIEW ' || cur_rec.view_name;
   END LOOP;
END;
/

-- Drop all existing tables safely in cascade order
BEGIN
   FOR cur_rec IN (SELECT table_name FROM user_tables WHERE table_name LIKE 'HIS_%') LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS PURGE';
   END LOOP;
END;
/

-- Drop all existing sequences safely
BEGIN
   FOR cur_rec IN (SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'HIS_%') LOOP
      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || cur_rec.sequence_name;
   END LOOP;
END;
/

-- =====================================================
-- SECTION 2: CREATE SEQUENCES
-- =====================================================

CREATE SEQUENCE HIS_ADMIN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_VENDOR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_DOCS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_PATIENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_PHARM_CAT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_PHARM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_ACCOUNTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_ASSETS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_EQUIPMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_LAB_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_MEDICAL_REC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_TRANSFER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_PAYROLL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_PRESCRIPTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_PWDRESET_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_SURGERY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_VITALS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_ROLES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_PRIVILEGES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_ROLE_PRIV_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE HIS_USER_ROLES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- =====================================================
-- SECTION 3: CORE TABLES & IDENTITY CONSTRAINTS
-- =====================================================

-- -----------------------------------------------------
-- TABLE 1: HIS_ADMIN (Administrators)
-- -----------------------------------------------------
CREATE TABLE HIS_ADMIN (
    AD_ID NUMBER PRIMARY KEY,
    AD_FNAME VARCHAR2(200) NOT NULL,
    AD_LNAME VARCHAR2(200) NOT NULL,
    AD_EMAIL VARCHAR2(200) NOT NULL UNIQUE,
    AD_PWD VARCHAR2(200) NOT NULL,
    AD_DPIC VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_AD_EMAIL CHECK (AD_EMAIL LIKE '%@%.%'),
    CONSTRAINT CHK_AD_FNAME CHECK (LENGTH(AD_FNAME) >= 1),
    CONSTRAINT CHK_AD_LNAME CHECK (LENGTH(AD_LNAME) >= 1)
);

CREATE OR REPLACE TRIGGER HIS_ADMIN_TRG
BEFORE INSERT ON HIS_ADMIN
FOR EACH ROW
BEGIN
    IF :NEW.AD_ID IS NULL THEN
        SELECT HIS_ADMIN_SEQ.NEXTVAL INTO :NEW.AD_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 2: HIS_VENDOR (Suppliers & Contractors)
-- -----------------------------------------------------
CREATE TABLE HIS_VENDOR (
    V_ID NUMBER PRIMARY KEY,
    V_NUMBER VARCHAR2(200) UNIQUE,
    V_NAME VARCHAR2(200) NOT NULL UNIQUE,
    V_ADR VARCHAR2(500),
    V_MOBILE VARCHAR2(200),
    V_EMAIL VARCHAR2(200),
    V_PHONE VARCHAR2(200),
    V_DESC VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_V_EMAIL CHECK (V_EMAIL LIKE '%@%.%'),
    CONSTRAINT CHK_V_NAME_LENGTH CHECK (LENGTH(V_NAME) >= 2)
);

CREATE OR REPLACE TRIGGER HIS_VENDOR_TRG
BEFORE INSERT ON HIS_VENDOR
FOR EACH ROW
BEGIN
    IF :NEW.V_ID IS NULL THEN
        SELECT HIS_VENDOR_SEQ.NEXTVAL INTO :NEW.V_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 3: HIS_DOCS (Doctors & Clinical Specialists)
-- -----------------------------------------------------
CREATE TABLE HIS_DOCS (
    DOC_ID NUMBER PRIMARY KEY,
    DOC_FNAME VARCHAR2(200) NOT NULL,
    DOC_LNAME VARCHAR2(200) NOT NULL,
    DOC_EMAIL VARCHAR2(200) NOT NULL UNIQUE,
    DOC_PWD VARCHAR2(200) NOT NULL,
    DOC_DEPT VARCHAR2(200),
    DOC_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    DOC_DPIC VARCHAR2(500),
    DOC_SPECIALIZATION VARCHAR2(200),
    DOC_PHONE VARCHAR2(200),
    DOC_STATUS VARCHAR2(50) DEFAULT 'Active',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_DOC_STATUS CHECK (DOC_STATUS IN ('Active', 'Inactive', 'On Leave')),
    CONSTRAINT CHK_DOC_EMAIL CHECK (DOC_EMAIL LIKE '%@%.%')
);

CREATE OR REPLACE TRIGGER HIS_DOCS_TRG
BEFORE INSERT ON HIS_DOCS
FOR EACH ROW
BEGIN
    IF :NEW.DOC_ID IS NULL THEN
        SELECT HIS_DOCS_SEQ.NEXTVAL INTO :NEW.DOC_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 4: HIS_PATIENTS (Patients & Admitted Cases)
-- -----------------------------------------------------
CREATE TABLE HIS_PATIENTS (
    PAT_ID NUMBER PRIMARY KEY,
    PAT_FNAME VARCHAR2(200) NOT NULL,
    PAT_LNAME VARCHAR2(200) NOT NULL,
    PAT_DOB DATE,
    PAT_AGE NUMBER,
    PAT_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    PAT_ADDR VARCHAR2(500),
    PAT_PHONE VARCHAR2(200),
    PAT_EMAIL VARCHAR2(200),
    PAT_TYPE VARCHAR2(50),
    PAT_ASSIGNED_DOC VARCHAR2(200),
    PAT_DATE_JOINED TIMESTAMP DEFAULT SYSTIMESTAMP,
    PAT_AILMENT VARCHAR2(500),
    PAT_DISCHARGE_STATUS VARCHAR2(50),
    PAT_GENDER VARCHAR2(20),
    PAT_BLOOD_GROUP VARCHAR2(10),
    PAT_EMERGENCY_CONTACT VARCHAR2(200),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_PAT_TYPE CHECK (PAT_TYPE IN ('InPatient', 'OutPatient')),
    CONSTRAINT CHK_PAT_GENDER CHECK (PAT_GENDER IN ('Male', 'Female', 'Other')),
    CONSTRAINT CHK_PAT_AGE CHECK (PAT_AGE >= 0 AND PAT_AGE <= 150),
    CONSTRAINT FK_PAT_DOC FOREIGN KEY (PAT_ASSIGNED_DOC) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE SET NULL
);

CREATE OR REPLACE TRIGGER HIS_PATIENTS_TRG
BEFORE INSERT ON HIS_PATIENTS
FOR EACH ROW
BEGIN
    IF :NEW.PAT_ID IS NULL THEN
        SELECT HIS_PATIENTS_SEQ.NEXTVAL INTO :NEW.PAT_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 5: HIS_PHARMACEUTICALS_CATEGORIES
-- -----------------------------------------------------
CREATE TABLE HIS_PHARMACEUTICALS_CATEGORIES (
    PHARM_CAT_ID NUMBER PRIMARY KEY,
    PHARM_CAT_NAME VARCHAR2(200) NOT NULL UNIQUE,
    PHARM_CAT_VENDOR VARCHAR2(200),
    PHARM_CAT_DESC VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER HIS_PHARM_CAT_TRG
BEFORE INSERT ON HIS_PHARMACEUTICALS_CATEGORIES
FOR EACH ROW
BEGIN
    IF :NEW.PHARM_CAT_ID IS NULL THEN
        SELECT HIS_PHARM_CAT_SEQ.NEXTVAL INTO :NEW.PHARM_CAT_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 6: HIS_PHARMACEUTICALS (Medicines & Inventory)
-- -----------------------------------------------------
CREATE TABLE HIS_PHARMACEUTICALS (
    PHAR_ID NUMBER PRIMARY KEY,
    PHAR_NAME VARCHAR2(200) NOT NULL,
    PHAR_BCODE VARCHAR2(200) UNIQUE,
    PHAR_DESC VARCHAR2(1000),
    PHAR_QTY NUMBER DEFAULT 0,
    PHAR_UNIT_PRICE NUMBER(10,2),
    PHAR_CAT VARCHAR2(200),
    PHAR_VENDOR VARCHAR2(200),
    PHAR_EXPIRY_DATE DATE,
    PHAR_MANUFACTURING_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PHAR_VENDOR FOREIGN KEY (PHAR_VENDOR) 
        REFERENCES HIS_VENDOR(V_NAME) ON DELETE SET NULL,
    CONSTRAINT FK_PHAR_CAT FOREIGN KEY (PHAR_CAT) 
        REFERENCES HIS_PHARMACEUTICALS_CATEGORIES(PHARM_CAT_NAME) ON DELETE SET NULL,
    CONSTRAINT CHK_PHAR_QTY CHECK (PHAR_QTY >= 0),
    CONSTRAINT CHK_PHAR_PRICE CHECK (PHAR_UNIT_PRICE >= 0),
    CONSTRAINT CHK_PHAR_DATES CHECK (PHAR_EXPIRY_DATE > PHAR_MANUFACTURING_DATE)
);

CREATE OR REPLACE TRIGGER HIS_PHARM_TRG
BEFORE INSERT ON HIS_PHARMACEUTICALS
FOR EACH ROW
BEGIN
    IF :NEW.PHAR_ID IS NULL THEN
        SELECT HIS_PHARM_SEQ.NEXTVAL INTO :NEW.PHAR_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 7: HIS_ACCOUNTS (Ledgers & Banking)
-- -----------------------------------------------------
CREATE TABLE HIS_ACCOUNTS (
    ACC_ID NUMBER PRIMARY KEY,
    ACC_NAME VARCHAR2(200) NOT NULL,
    ACC_DESC VARCHAR2(1000),
    ACC_TYPE VARCHAR2(100),
    ACC_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    ACC_AMOUNT NUMBER(15,2) DEFAULT 0,
    ACC_CURRENCY VARCHAR2(10) DEFAULT 'USD',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_ACC_TYPE CHECK (ACC_TYPE IN ('Payable Account', 'Receivable Account', 'Asset Account', 'Liability Account', 'Equity Account')),
    CONSTRAINT CHK_ACC_CURRENCY CHECK (ACC_CURRENCY IN ('USD', 'EUR', 'GBP', 'INR'))
);

CREATE OR REPLACE TRIGGER HIS_ACCOUNTS_TRG
BEFORE INSERT ON HIS_ACCOUNTS
FOR EACH ROW
BEGIN
    IF :NEW.ACC_ID IS NULL THEN
        SELECT HIS_ACCOUNTS_SEQ.NEXTVAL INTO :NEW.ACC_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 8: HIS_ASSETS (Hospital Capital Assets)
-- -----------------------------------------------------
CREATE TABLE HIS_ASSETS (
    ASST_ID NUMBER PRIMARY KEY,
    ASST_NAME VARCHAR2(200) NOT NULL,
    ASST_DESC VARCHAR2(1000),
    ASST_VENDOR VARCHAR2(200),
    ASST_STATUS VARCHAR2(50) DEFAULT 'Active',
    ASST_DEPT VARCHAR2(200),
    ASST_PURCHASE_DATE DATE,
    ASST_PURCHASE_COST NUMBER(12,2),
    ASST_SERIAL_NUMBER VARCHAR2(200) UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ASST_VENDOR FOREIGN KEY (ASST_VENDOR) 
        REFERENCES HIS_VENDOR(V_NAME) ON DELETE SET NULL,
    CONSTRAINT CHK_ASST_STATUS CHECK (ASST_STATUS IN ('Active', 'Maintenance', 'Retired', 'Broken')),
    CONSTRAINT CHK_ASST_COST CHECK (ASST_PURCHASE_COST >= 0)
);

CREATE OR REPLACE TRIGGER HIS_ASSETS_TRG
BEFORE INSERT ON HIS_ASSETS
FOR EACH ROW
BEGIN
    IF :NEW.ASST_ID IS NULL THEN
        SELECT HIS_ASSETS_SEQ.NEXTVAL INTO :NEW.ASST_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 9: HIS_EQUIPMENTS (Biomedical Equipment)
-- -----------------------------------------------------
CREATE TABLE HIS_EQUIPMENTS (
    EQP_ID NUMBER PRIMARY KEY,
    EQP_CODE VARCHAR2(200) UNIQUE,
    EQP_NAME VARCHAR2(200) NOT NULL,
    EQP_VENDOR VARCHAR2(200),
    EQP_DESC VARCHAR2(1000),
    EQP_DEPT VARCHAR2(200),
    EQP_STATUS VARCHAR2(50) DEFAULT 'Functioning',
    EQP_QTY NUMBER DEFAULT 0,
    EQP_LOCATION VARCHAR2(200),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_EQP_VENDOR FOREIGN KEY (EQP_VENDOR) 
        REFERENCES HIS_VENDOR(V_NAME) ON DELETE SET NULL,
    CONSTRAINT CHK_EQP_STATUS CHECK (EQP_STATUS IN ('Functioning', 'Under Repair', 'Out of Service', 'Reserved')),
    CONSTRAINT CHK_EQP_QTY CHECK (EQP_QTY >= 0)
);

CREATE OR REPLACE TRIGGER HIS_EQUIPMENT_TRG
BEFORE INSERT ON HIS_EQUIPMENTS
FOR EACH ROW
BEGIN
    IF :NEW.EQP_ID IS NULL THEN
        SELECT HIS_EQUIPMENT_SEQ.NEXTVAL INTO :NEW.EQP_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 10: HIS_LABORATORY (Laboratory Diagnostic Tests)
-- -----------------------------------------------------
CREATE TABLE HIS_LABORATORY (
    LAB_ID NUMBER PRIMARY KEY,
    LAB_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    LAB_PAT_NUMBER VARCHAR2(200) NOT NULL,
    LAB_DOC_NUMBER VARCHAR2(200),
    LAB_PAT_TESTS VARCHAR2(1000),
    LAB_PAT_RESULTS VARCHAR2(4000),
    LAB_STATUS VARCHAR2(50) DEFAULT 'Pending',
    LAB_DATE_REC TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAB_COMPLETED_DATE TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LAB_PAT FOREIGN KEY (LAB_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE CASCADE,
    CONSTRAINT FK_LAB_DOC FOREIGN KEY (LAB_DOC_NUMBER) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE SET NULL,
    CONSTRAINT CHK_LAB_STATUS CHECK (LAB_STATUS IN ('Pending', 'In Progress', 'Completed', 'Cancelled'))
);

CREATE OR REPLACE TRIGGER HIS_LAB_TRG
BEFORE INSERT ON HIS_LABORATORY
FOR EACH ROW
BEGIN
    IF :NEW.LAB_ID IS NULL THEN
        SELECT HIS_LAB_SEQ.NEXTVAL INTO :NEW.LAB_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 11: HIS_MEDICAL_RECORDS (Patient Clinical History)
-- -----------------------------------------------------
CREATE TABLE HIS_MEDICAL_RECORDS (
    MDR_ID NUMBER PRIMARY KEY,
    MDR_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    MDR_PAT_NUMBER VARCHAR2(200) NOT NULL,
    MDR_DOC_NUMBER VARCHAR2(200),
    MDR_PAT_PRESCR VARCHAR2(2000),
    MDR_DIAGNOSIS VARCHAR2(2000),
    MDR_TREATMENT_PLAN VARCHAR2(2000),
    MDR_DATE_REC TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_MDR_PAT FOREIGN KEY (MDR_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE CASCADE,
    CONSTRAINT FK_MDR_DOC FOREIGN KEY (MDR_DOC_NUMBER) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE SET NULL
);

CREATE OR REPLACE TRIGGER HIS_MEDICAL_REC_TRG
BEFORE INSERT ON HIS_MEDICAL_RECORDS
FOR EACH ROW
BEGIN
    IF :NEW.MDR_ID IS NULL THEN
        SELECT HIS_MEDICAL_REC_SEQ.NEXTVAL INTO :NEW.MDR_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 12: HIS_PATIENT_TRANSFER (Ward & Facility Transfers)
-- -----------------------------------------------------
CREATE TABLE HIS_PATIENT_TRANSFER (
    PT_ID NUMBER PRIMARY KEY,
    PT_PAT_NUMBER VARCHAR2(200),
    PT_FROM_WARD VARCHAR2(200),
    PT_TO_WARD VARCHAR2(200),
    PT_REASON VARCHAR2(1000),
    PT_TRANSFER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    PT_AUTHORIZED_BY VARCHAR2(200),
    PT_STATUS VARCHAR2(50) DEFAULT 'Pending',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_TRANSFER_PAT FOREIGN KEY (PT_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE SET NULL,
    CONSTRAINT CHK_TRANSFER_STATUS CHECK (PT_STATUS IN ('Pending', 'Completed', 'Cancelled'))
);

CREATE OR REPLACE TRIGGER HIS_TRANSFER_TRG
BEFORE INSERT ON HIS_PATIENT_TRANSFER
FOR EACH ROW
BEGIN
    IF :NEW.PT_ID IS NULL THEN
        SELECT HIS_TRANSFER_SEQ.NEXTVAL INTO :NEW.PT_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 13: HIS_PAYROLLS (Physician & Staff Compensation)
-- -----------------------------------------------------
CREATE TABLE HIS_PAYROLLS (
    PAY_ID NUMBER PRIMARY KEY,
    PAY_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    PAY_DOC_NUMBER VARCHAR2(200) NOT NULL,
    PAY_AMOUNT NUMBER(12,2),
    PAY_PERIOD VARCHAR2(100),
    PAY_STATUS VARCHAR2(50) DEFAULT 'Pending',
    PAY_DATE DATE,
    PAY_METHOD VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PAY_DOC FOREIGN KEY (PAY_DOC_NUMBER) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE CASCADE,
    CONSTRAINT CHK_PAY_STATUS CHECK (PAY_STATUS IN ('Pending', 'Paid', 'Cancelled', 'On Hold')),
    CONSTRAINT CHK_PAY_METHOD CHECK (PAY_METHOD IN ('Bank Transfer', 'Check', 'Cash', 'Direct Deposit')),
    CONSTRAINT CHK_PAY_AMOUNT CHECK (PAY_AMOUNT > 0)
);

CREATE OR REPLACE TRIGGER HIS_PAYROLL_TRG
BEFORE INSERT ON HIS_PAYROLLS
FOR EACH ROW
BEGIN
    IF :NEW.PAY_ID IS NULL THEN
        SELECT HIS_PAYROLL_SEQ.NEXTVAL INTO :NEW.PAY_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 14: HIS_PRESCRIPTIONS (Medication Regimens)
-- -----------------------------------------------------
CREATE TABLE HIS_PRESCRIPTIONS (
    PRES_ID NUMBER PRIMARY KEY,
    PRES_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    PRES_PAT_NUMBER VARCHAR2(200) NOT NULL,
    PRES_DOC_NUMBER VARCHAR2(200),
    PRES_MEDICATION VARCHAR2(500),
    PRES_DOSAGE VARCHAR2(200),
    PRES_FREQUENCY VARCHAR2(200),
    PRES_DURATION VARCHAR2(200),
    PRES_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRES_STATUS VARCHAR2(50) DEFAULT 'Active',
    PRES_REFILLS_REMAINING NUMBER DEFAULT 0,
    PRES_NOTES VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PRES_PAT FOREIGN KEY (PRES_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE CASCADE,
    CONSTRAINT FK_PRES_DOC FOREIGN KEY (PRES_DOC_NUMBER) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE SET NULL,
    CONSTRAINT CHK_PRES_STATUS CHECK (PRES_STATUS IN ('Active', 'Completed', 'Cancelled', 'Expired'))
);

CREATE OR REPLACE TRIGGER HIS_PRESCRIPTION_TRG
BEFORE INSERT ON HIS_PRESCRIPTIONS
FOR EACH ROW
BEGIN
    IF :NEW.PRES_ID IS NULL THEN
        SELECT HIS_PRESCRIPTION_SEQ.NEXTVAL INTO :NEW.PRES_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 15: HIS_PWDRESETS (Password Reset Tokens)
-- -----------------------------------------------------
CREATE TABLE HIS_PWDRESETS (
    ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(200) NOT NULL,
    RESET_TOKEN VARCHAR2(200),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    EXPIRES_AT TIMESTAMP
);

CREATE OR REPLACE TRIGGER HIS_PWDRESET_TRG
BEFORE INSERT ON HIS_PWDRESETS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT HIS_PWDRESET_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 16: HIS_SURGERY (Surgical Operations & Procedures)
-- -----------------------------------------------------
CREATE TABLE HIS_SURGERY (
    SURG_ID NUMBER PRIMARY KEY,
    SURG_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    SURG_PAT_NUMBER VARCHAR2(200) NOT NULL,
    SURG_DOC_NUMBER VARCHAR2(200),
    SURG_TYPE VARCHAR2(200),
    SURG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    SURG_DURATION VARCHAR2(100),
    SURG_STATUS VARCHAR2(50) DEFAULT 'Scheduled',
    SURG_NOTES VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_SURG_PAT FOREIGN KEY (SURG_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE CASCADE,
    CONSTRAINT FK_SURG_DOC FOREIGN KEY (SURG_DOC_NUMBER) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE SET NULL,
    CONSTRAINT CHK_SURG_STATUS CHECK (SURG_STATUS IN ('Scheduled', 'In Progress', 'Completed', 'Cancelled'))
);

CREATE OR REPLACE TRIGGER HIS_SURGERY_TRG
BEFORE INSERT ON HIS_SURGERY
FOR EACH ROW
BEGIN
    IF :NEW.SURG_ID IS NULL THEN
        SELECT HIS_SURGERY_SEQ.NEXTVAL INTO :NEW.SURG_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 17: HIS_VITALS (Patient Biometrics)
-- -----------------------------------------------------
CREATE TABLE HIS_VITALS (
    VIT_ID NUMBER PRIMARY KEY,
    VIT_PAT_NUMBER VARCHAR2(200) NOT NULL,
    VIT_BODYTEMP NUMBER(5,2),
    VIT_HEARTPULSE NUMBER,
    VIT_RESPIRATION NUMBER,
    VIT_WEIGHT NUMBER(6,2),
    VIT_BLOOD_PRESSURE VARCHAR2(20),
    VIT_OXYGEN_SAT NUMBER(5,2),
    VIT_RECORDED_BY VARCHAR2(200),
    VIT_RECORDED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_VIT_PAT FOREIGN KEY (VIT_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE CASCADE,
    CONSTRAINT CHK_VIT_TEMP CHECK (VIT_BODYTEMP BETWEEN 80 AND 115),
    CONSTRAINT CHK_VIT_PULSE CHECK (VIT_HEARTPULSE BETWEEN 30 AND 250),
    CONSTRAINT CHK_VIT_RESP CHECK (VIT_RESPIRATION BETWEEN 5 AND 65),
    CONSTRAINT CHK_VIT_WEIGHT CHECK (VIT_WEIGHT > 0),
    CONSTRAINT CHK_VIT_O2 CHECK (VIT_OXYGEN_SAT BETWEEN 0 AND 100)
);

CREATE OR REPLACE TRIGGER HIS_VITALS_TRG
BEFORE INSERT ON HIS_VITALS
FOR EACH ROW
BEGIN
    IF :NEW.VIT_ID IS NULL THEN
        SELECT HIS_VITALS_SEQ.NEXTVAL INTO :NEW.VIT_ID FROM DUAL;
    END IF;
END;
/

-- -----------------------------------------------------
-- TABLE 18-22: RBAC (ROLES, PRIVILEGES, USERS)
-- -----------------------------------------------------
CREATE TABLE HIS_ROLES (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR2(100) NOT NULL UNIQUE,
    ROLE_DESC VARCHAR2(1000),
    ROLE_LEVEL NUMBER DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_ROLE_LEVEL CHECK (ROLE_LEVEL BETWEEN 1 AND 10),
    CONSTRAINT CHK_ROLE_NAME CHECK (LENGTH(ROLE_NAME) >= 2)
);

CREATE OR REPLACE TRIGGER HIS_ROLES_TRG
BEFORE INSERT ON HIS_ROLES
FOR EACH ROW
BEGIN
    IF :NEW.ROLE_ID IS NULL THEN
        SELECT HIS_ROLES_SEQ.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE HIS_PRIVILEGES (
    PRIV_ID NUMBER PRIMARY KEY,
    PRIV_NAME VARCHAR2(100) NOT NULL UNIQUE,
    PRIV_DESC VARCHAR2(1000),
    PRIV_MODULE VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER HIS_PRIVILEGES_TRG
BEFORE INSERT ON HIS_PRIVILEGES
FOR EACH ROW
BEGIN
    IF :NEW.PRIV_ID IS NULL THEN
        SELECT HIS_PRIVILEGES_SEQ.NEXTVAL INTO :NEW.PRIV_ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE HIS_ROLE_PRIVILEGES (
    RP_ID NUMBER PRIMARY KEY,
    ROLE_ID NUMBER NOT NULL,
    PRIV_ID NUMBER NOT NULL,
    GRANTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    GRANTED_BY VARCHAR2(200),
    CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID) 
        REFERENCES HIS_ROLES(ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RP_PRIV FOREIGN KEY (PRIV_ID) 
        REFERENCES HIS_PRIVILEGES(PRIV_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_ROLE_PRIV UNIQUE (ROLE_ID, PRIV_ID)
);

CREATE OR REPLACE TRIGGER HIS_ROLE_PRIV_TRG
BEFORE INSERT ON HIS_ROLE_PRIVILEGES
FOR EACH ROW
BEGIN
    IF :NEW.RP_ID IS NULL THEN
        SELECT HIS_ROLE_PRIV_SEQ.NEXTVAL INTO :NEW.RP_ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE HIS_USERS (
    USER_ID NUMBER PRIMARY KEY,
    USER_EMAIL VARCHAR2(200) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(200) NOT NULL,
    USER_ROLE_ID NUMBER,
    USER_FNAME VARCHAR2(200) NOT NULL,
    USER_LNAME VARCHAR2(200) NOT NULL,
    USER_STATUS VARCHAR2(50) DEFAULT 'Active',
    USER_LAST_LOGIN TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (USER_ROLE_ID) 
        REFERENCES HIS_ROLES(ROLE_ID) ON DELETE SET NULL,
    CONSTRAINT CHK_USER_STATUS CHECK (USER_STATUS IN ('Active', 'Inactive', 'Suspended', 'Locked')),
    CONSTRAINT CHK_USER_EMAIL CHECK (USER_EMAIL LIKE '%@%.%')
);

CREATE OR REPLACE TRIGGER HIS_USERS_TRG
BEFORE INSERT ON HIS_USERS
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        SELECT HIS_USERS_SEQ.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE HIS_USER_ROLES (
    UR_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    ASSIGNED_BY VARCHAR2(200),
    CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) 
        REFERENCES HIS_USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) 
        REFERENCES HIS_ROLES(ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_USER_ROLE UNIQUE (USER_ID, ROLE_ID)
);

CREATE OR REPLACE TRIGGER HIS_USER_ROLES_TRG
BEFORE INSERT ON HIS_USER_ROLES
FOR EACH ROW
BEGIN
    IF :NEW.UR_ID IS NULL THEN
        SELECT HIS_USER_ROLES_SEQ.NEXTVAL INTO :NEW.UR_ID FROM DUAL;
    END IF;
END;
/

-- =====================================================
-- SECTION 4: PERFORMANCE OPTIMIZATION INDEXES
-- =====================================================

CREATE INDEX IDX_PAT_ASSIGNED_DOC ON HIS_PATIENTS(PAT_ASSIGNED_DOC);
CREATE INDEX IDX_PAT_TYPE ON HIS_PATIENTS(PAT_TYPE);
CREATE INDEX IDX_PRES_PAT_NUMBER ON HIS_PRESCRIPTIONS(PRES_PAT_NUMBER);
CREATE INDEX IDX_PRES_DOC_NUMBER ON HIS_PRESCRIPTIONS(PRES_DOC_NUMBER);
CREATE INDEX IDX_LAB_PAT_NUMBER ON HIS_LABORATORY(LAB_PAT_NUMBER);
CREATE INDEX IDX_LAB_DOC_NUMBER ON HIS_LABORATORY(LAB_DOC_NUMBER);
CREATE INDEX IDX_VIT_PAT_NUMBER ON HIS_VITALS(VIT_PAT_NUMBER);
CREATE INDEX IDX_SURG_PAT_NUMBER ON HIS_SURGERY(SURG_PAT_NUMBER);
CREATE INDEX IDX_MDR_PAT_NUMBER ON HIS_MEDICAL_RECORDS(MDR_PAT_NUMBER);
CREATE INDEX IDX_TRANSFER_PAT_NUMBER ON HIS_PATIENT_TRANSFER(PT_PAT_NUMBER);

-- =====================================================
-- SECTION 5: 3NF RELATIONAL VIEWS (REAL-TIME JOINS)
-- =====================================================

CREATE OR REPLACE VIEW V_LABORATORY AS
SELECT 
    l.LAB_ID,
    l.LAB_NUMBER,
    l.LAB_PAT_NUMBER,
    p.PAT_FNAME || ' ' || p.PAT_LNAME AS LAB_PAT_NAME,
    p.PAT_AILMENT AS LAB_PAT_AILMENT,
    p.PAT_EMAIL AS LAB_PAT_EMAIL,
    p.PAT_PHONE AS LAB_PAT_PHONE,
    p.PAT_AGE AS LAB_PAT_AGE,
    p.PAT_GENDER AS LAB_PAT_GENDER,
    l.LAB_DOC_NUMBER,
    d.DOC_FNAME || ' ' || d.DOC_LNAME AS LAB_DOC_NAME,
    d.DOC_EMAIL AS LAB_DOC_EMAIL,
    d.DOC_DEPT AS LAB_DOC_DEPT,
    l.LAB_PAT_TESTS,
    l.LAB_PAT_RESULTS,
    l.LAB_STATUS,
    l.LAB_DATE_REC,
    l.LAB_COMPLETED_DATE,
    l.CREATED_AT,
    l.UPDATED_AT
FROM HIS_LABORATORY l
LEFT JOIN HIS_PATIENTS p ON l.LAB_PAT_NUMBER = p.PAT_NUMBER
LEFT JOIN HIS_DOCS d ON l.LAB_DOC_NUMBER = d.DOC_NUMBER;

CREATE OR REPLACE VIEW V_MEDICAL_RECORDS AS
SELECT 
    m.MDR_ID,
    m.MDR_NUMBER,
    m.MDR_PAT_NUMBER,
    p.PAT_FNAME || ' ' || p.PAT_LNAME AS MDR_PAT_NAME,
    p.PAT_ADDR AS MDR_PAT_ADR,
    p.PAT_AGE AS MDR_PAT_AGE,
    p.PAT_AILMENT AS MDR_PAT_AILMENT,
    p.PAT_EMAIL AS MDR_PAT_EMAIL,
    p.PAT_PHONE AS MDR_PAT_PHONE,
    p.PAT_GENDER AS MDR_PAT_GENDER,
    p.PAT_BLOOD_GROUP AS MDR_PAT_BLOOD_GROUP,
    m.MDR_DOC_NUMBER,
    d.DOC_FNAME || ' ' || d.DOC_LNAME AS MDR_DOC_NAME,
    d.DOC_EMAIL AS MDR_DOC_EMAIL,
    d.DOC_DEPT AS MDR_DOC_DEPT,
    m.MDR_PAT_PRESCR,
    m.MDR_DIAGNOSIS,
    m.MDR_TREATMENT_PLAN,
    m.MDR_DATE_REC,
    m.CREATED_AT,
    m.UPDATED_AT
FROM HIS_MEDICAL_RECORDS m
LEFT JOIN HIS_PATIENTS p ON m.MDR_PAT_NUMBER = p.PAT_NUMBER
LEFT JOIN HIS_DOCS d ON m.MDR_DOC_NUMBER = d.DOC_NUMBER;

CREATE OR REPLACE VIEW V_PATIENT_TRANSFER AS
SELECT 
    t.PT_ID,
    t.PT_PAT_NUMBER,
    p.PAT_FNAME || ' ' || p.PAT_LNAME AS PT_PAT_NAME,
    p.PAT_EMAIL AS PT_PAT_EMAIL,
    p.PAT_PHONE AS PT_PAT_PHONE,
    p.PAT_TYPE AS PT_PAT_TYPE,
    t.PT_FROM_WARD,
    t.PT_TO_WARD,
    t.PT_REASON,
    t.PT_TRANSFER_DATE,
    t.PT_AUTHORIZED_BY,
    d.DOC_FNAME || ' ' || d.DOC_LNAME AS PT_AUTHORIZED_DOC_NAME,
    d.DOC_EMAIL AS PT_AUTHORIZED_DOC_EMAIL,
    t.PT_STATUS,
    t.CREATED_AT,
    t.UPDATED_AT
FROM HIS_PATIENT_TRANSFER t
LEFT JOIN HIS_PATIENTS p ON t.PT_PAT_NUMBER = p.PAT_NUMBER
LEFT JOIN HIS_DOCS d ON t.PT_AUTHORIZED_BY = d.DOC_NUMBER;

CREATE OR REPLACE VIEW V_PAYROLLS AS
SELECT 
    pay.PAY_ID,
    pay.PAY_NUMBER,
    pay.PAY_DOC_NUMBER,
    d.DOC_FNAME || ' ' || d.DOC_LNAME AS PAY_DOC_NAME,
    d.DOC_EMAIL AS PAY_DOC_EMAIL,
    d.DOC_PHONE AS PAY_DOC_PHONE,
    d.DOC_DEPT AS PAY_DOC_DEPT,
    pay.PAY_AMOUNT,
    pay.PAY_PERIOD,
    pay.PAY_STATUS,
    pay.PAY_DATE,
    pay.PAY_METHOD,
    pay.CREATED_AT,
    pay.UPDATED_AT
FROM HIS_PAYROLLS pay
LEFT JOIN HIS_DOCS d ON pay.PAY_DOC_NUMBER = d.DOC_NUMBER;

CREATE OR REPLACE VIEW V_PRESCRIPTIONS AS
SELECT 
    pr.PRES_ID,
    pr.PRES_NUMBER,
    pr.PRES_PAT_NUMBER,
    p.PAT_FNAME || ' ' || p.PAT_LNAME AS PRES_PAT_NAME,
    p.PAT_EMAIL AS PRES_PAT_EMAIL,
    p.PAT_PHONE AS PRES_PAT_PHONE,
    p.PAT_AGE AS PRES_PAT_AGE,
    p.PAT_GENDER AS PRES_PAT_GENDER,
    pr.PRES_DOC_NUMBER,
    d.DOC_FNAME || ' ' || d.DOC_LNAME AS PRES_DOC_NAME,
    d.DOC_EMAIL AS PRES_DOC_EMAIL,
    d.DOC_DEPT AS PRES_DOC_DEPT,
    pr.PRES_MEDICATION,
    pr.PRES_DOSAGE,
    pr.PRES_FREQUENCY,
    pr.PRES_DURATION,
    pr.PRES_DATE,
    pr.PRES_STATUS,
    pr.PRES_REFILLS_REMAINING,
    pr.PRES_NOTES,
    pr.CREATED_AT,
    pr.UPDATED_AT
FROM HIS_PRESCRIPTIONS pr
LEFT JOIN HIS_PATIENTS p ON pr.PRES_PAT_NUMBER = p.PAT_NUMBER
LEFT JOIN HIS_DOCS d ON pr.PRES_DOC_NUMBER = d.DOC_NUMBER;

CREATE OR REPLACE VIEW V_SURGERY AS
SELECT 
    s.SURG_ID,
    s.SURG_NUMBER,
    s.SURG_PAT_NUMBER,
    p.PAT_FNAME || ' ' || p.PAT_LNAME AS SURG_PAT_NAME,
    p.PAT_EMAIL AS SURG_PAT_EMAIL,
    p.PAT_PHONE AS SURG_PAT_PHONE,
    p.PAT_AGE AS SURG_PAT_AGE,
    p.PAT_BLOOD_GROUP AS SURG_PAT_BLOOD_GROUP,
    s.SURG_DOC_NUMBER,
    d.DOC_FNAME || ' ' || d.DOC_LNAME AS SURG_DOC_NAME,
    d.DOC_EMAIL AS SURG_DOC_EMAIL,
    d.DOC_DEPT AS SURG_DOC_DEPT,
    s.SURG_TYPE,
    s.SURG_DATE,
    s.SURG_DURATION,
    s.SURG_STATUS,
    s.SURG_NOTES,
    s.CREATED_AT,
    s.UPDATED_AT
FROM HIS_SURGERY s
LEFT JOIN HIS_PATIENTS p ON s.SURG_PAT_NUMBER = p.PAT_NUMBER
LEFT JOIN HIS_DOCS d ON s.SURG_DOC_NUMBER = d.DOC_NUMBER;

CREATE OR REPLACE VIEW V_VITALS AS
SELECT 
    v.VIT_ID,
    v.VIT_PAT_NUMBER,
    p.PAT_FNAME || ' ' || p.PAT_LNAME AS VIT_PAT_NAME,
    p.PAT_EMAIL AS VIT_PAT_EMAIL,
    p.PAT_PHONE AS VIT_PAT_PHONE,
    p.PAT_AGE AS VIT_PAT_AGE,
    p.PAT_BLOOD_GROUP AS VIT_PAT_BLOOD_GROUP,
    v.VIT_BODYTEMP,
    v.VIT_HEARTPULSE,
    v.VIT_RESPIRATION,
    v.VIT_WEIGHT,
    v.VIT_BLOOD_PRESSURE,
    v.VIT_OXYGEN_SAT,
    v.VIT_RECORDED_BY,
    v.VIT_RECORDED_DATE,
    v.CREATED_AT,
    v.UPDATED_AT
FROM HIS_VITALS v
LEFT JOIN HIS_PATIENTS p ON v.VIT_PAT_NUMBER = p.PAT_NUMBER;

CREATE OR REPLACE VIEW V_DOCTOR_PATIENTS AS
SELECT 
    d.DOC_NUMBER,
    d.DOC_FNAME || ' ' || d.DOC_LNAME AS DOCTOR_NAME,
    d.DOC_DEPT,
    p.PAT_NUMBER,
    p.PAT_FNAME || ' ' || p.PAT_LNAME AS PATIENT_NAME,
    p.PAT_AGE,
    p.PAT_PHONE,
    p.PAT_EMAIL,
    p.PAT_TYPE,
    p.PAT_AILMENT,
    p.PAT_DATE_JOINED
FROM HIS_DOCS d
INNER JOIN HIS_PATIENTS p ON d.DOC_NUMBER = p.PAT_ASSIGNED_DOC
WHERE d.DOC_STATUS = 'Active';

-- =====================================================
-- SECTION 6: POPULATE MASTER SEED DATA
-- =====================================================

-- Roles
INSERT INTO HIS_ROLES (ROLE_NAME, ROLE_DESC, ROLE_LEVEL) VALUES ('Admin', 'Full administrative authority across all clinical and operational subsystems', 10);
INSERT INTO HIS_ROLES (ROLE_NAME, ROLE_DESC, ROLE_LEVEL) VALUES ('Doctor', 'Attending physician with patient care, prescribing, and surgical authority', 7);
INSERT INTO HIS_ROLES (ROLE_NAME, ROLE_DESC, ROLE_LEVEL) VALUES ('Patient', 'Patient portal access for diagnostic history, prescriptions, and telemetry', 3);

-- Privileges
INSERT INTO HIS_PRIVILEGES (PRIV_NAME, PRIV_DESC, PRIV_MODULE) VALUES ('admin.all', 'Superuser system privileges', 'Admin');
INSERT INTO HIS_PRIVILEGES (PRIV_NAME, PRIV_DESC, PRIV_MODULE) VALUES ('doctor.view_patients', 'Inspect assigned patient clinical charts', 'Patients');
INSERT INTO HIS_PRIVILEGES (PRIV_NAME, PRIV_DESC, PRIV_MODULE) VALUES ('doctor.prescribe', 'Issue clinical prescriptions', 'Prescriptions');
INSERT INTO HIS_PRIVILEGES (PRIV_NAME, PRIV_DESC, PRIV_MODULE) VALUES ('doctor.view_vitals', 'Telemetry biometric vital monitoring', 'Vitals');
INSERT INTO HIS_PRIVILEGES (PRIV_NAME, PRIV_DESC, PRIV_MODULE) VALUES ('doctor.order_labs', 'Order and review pathology diagnostics', 'Laboratory');
INSERT INTO HIS_PRIVILEGES (PRIV_NAME, PRIV_DESC, PRIV_MODULE) VALUES ('patient.view_prescriptions', 'View active prescriptions and refills', 'Prescriptions');
INSERT INTO HIS_PRIVILEGES (PRIV_NAME, PRIV_DESC, PRIV_MODULE) VALUES ('patient.view_vitals', 'View biometric charts', 'Vitals');

-- Admin Account
INSERT INTO HIS_ADMIN (AD_FNAME, AD_LNAME, AD_EMAIL, AD_PWD) VALUES
('System', 'Administrator', 'admin@curewell.com', 'admin');

-- Vendors
INSERT INTO HIS_VENDOR (V_NUMBER, V_NAME, V_ADR, V_PHONE, V_EMAIL) VALUES ('VND001', 'MediSupply Corp', '123 Medical Plaza, New York, NY 10001', '+1-212-555-0100', 'contact@medisupply.com');
INSERT INTO HIS_VENDOR (V_NUMBER, V_NAME, V_ADR, V_PHONE, V_EMAIL) VALUES ('VND002', 'PharmaCare International', '456 Pharmacy Ave, Los Angeles, CA 90001', '+1-310-555-0200', 'sales@pharmacare.com');
INSERT INTO HIS_VENDOR (V_NUMBER, V_NAME, V_ADR, V_PHONE, V_EMAIL) VALUES ('VND003', 'HealthTech Solutions', '789 Innovation Dr, Boston, MA 02101', '+1-617-555-0300', 'info@healthtech.com');
INSERT INTO HIS_VENDOR (V_NUMBER, V_NAME, V_ADR, V_PHONE, V_EMAIL) VALUES ('VND004', 'Global Medical Supplies', '321 Commerce St, Chicago, IL 60601', '+1-312-555-0400', 'orders@globalmed.com');
INSERT INTO HIS_VENDOR (V_NUMBER, V_NAME, V_ADR, V_PHONE, V_EMAIL) VALUES ('VND005', 'Surgical Equipment Inc', '654 Industry Blvd, Houston, TX 77001', '+1-713-555-0500', 'sales@surgequip.com');
INSERT INTO HIS_VENDOR (V_NUMBER, V_NAME, V_ADR, V_PHONE, V_EMAIL) VALUES ('VND006', 'BioLab Diagnostics', '987 Research Pkwy, San Francisco, CA 94101', '+1-415-555-0600', 'contact@biolabdx.com');
INSERT INTO HIS_VENDOR (V_NUMBER, V_NAME, V_ADR, V_PHONE, V_EMAIL) VALUES ('VND007', 'CardioMed Devices', '147 Heart Lane, Seattle, WA 98101', '+1-206-555-0700', 'support@cardiomed.com');

-- Doctors (Including DOC-DEMO)
INSERT INTO HIS_DOCS (DOC_NUMBER, DOC_FNAME, DOC_LNAME, DOC_EMAIL, DOC_PWD, DOC_DEPT, DOC_SPECIALIZATION, DOC_PHONE, DOC_STATUS) VALUES
('DOC-DEMO', 'Alexander', 'Hayes', 'doctor@curewell.com', 'doctor', 'Cardiology & Internal Medicine', 'Senior Consultant Cardiologist & Physician', '+1 (555) 432-8890', 'Active');
INSERT INTO HIS_DOCS (DOC_NUMBER, DOC_FNAME, DOC_LNAME, DOC_EMAIL, DOC_PWD, DOC_DEPT, DOC_SPECIALIZATION, DOC_PHONE, DOC_STATUS) VALUES
('DOC001', 'Sarah', 'Jenkins', 's.jenkins@curewell.com', 'doctor', 'Cardiology', 'Interventional Cardiology', '+1-555-0101', 'Active');
INSERT INTO HIS_DOCS (DOC_NUMBER, DOC_FNAME, DOC_LNAME, DOC_EMAIL, DOC_PWD, DOC_DEPT, DOC_SPECIALIZATION, DOC_PHONE, DOC_STATUS) VALUES
('DOC002', 'Michael', 'Chang', 'm.chang@curewell.com', 'doctor', 'Neurology', 'Cerebrovascular & Stroke', '+1-555-0102', 'Active');
INSERT INTO HIS_DOCS (DOC_NUMBER, DOC_FNAME, DOC_LNAME, DOC_EMAIL, DOC_PWD, DOC_DEPT, DOC_SPECIALIZATION, DOC_PHONE, DOC_STATUS) VALUES
('DOC003', 'Emily', 'Rodriguez', 'e.rodriguez@curewell.com', 'doctor', 'Pediatrics', 'Neonatal Critical Care', '+1-555-0103', 'Active');
INSERT INTO HIS_DOCS (DOC_NUMBER, DOC_FNAME, DOC_LNAME, DOC_EMAIL, DOC_PWD, DOC_DEPT, DOC_SPECIALIZATION, DOC_PHONE, DOC_STATUS) VALUES
('DOC004', 'David', 'Kim', 'd.kim@curewell.com', 'doctor', 'Orthopedics', 'Reconstructive Joint Surgery', '+1-555-0104', 'Active');
INSERT INTO HIS_DOCS (DOC_NUMBER, DOC_FNAME, DOC_LNAME, DOC_EMAIL, DOC_PWD, DOC_DEPT, DOC_SPECIALIZATION, DOC_PHONE, DOC_STATUS) VALUES
('DOC005', 'Rachel', 'Patel', 'r.patel@curewell.com', 'doctor', 'Oncology', 'Surgical Oncology', '+1-555-0105', 'Active');

-- Patients (Including PAT-DEMO and Doctor Demo Cohort)
INSERT INTO HIS_PATIENTS (PAT_NUMBER, PAT_FNAME, PAT_LNAME, PAT_DOB, PAT_AGE, PAT_ADDR, PAT_PHONE, PAT_EMAIL, PAT_TYPE, PAT_ASSIGNED_DOC, PAT_AILMENT, PAT_DISCHARGE_STATUS, PAT_GENDER, PAT_BLOOD_GROUP, PAT_EMERGENCY_CONTACT) VALUES
('PAT-DEMO', 'Alex', 'Morgan', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 34, '742 Evergreen Terrace, Springfield, IL 62704', '+1 (555) 839-2041', 'demo.patient@curewell.com', 'InPatient', 'DOC-DEMO', 'Hypertensive Heart Disease & Exertional Angina', 'Admitted', 'Male', 'O+', 'Sarah Morgan (Spouse) - +1 (555) 839-2042');
INSERT INTO HIS_PATIENTS (PAT_NUMBER, PAT_FNAME, PAT_LNAME, PAT_DOB, PAT_AGE, PAT_ADDR, PAT_PHONE, PAT_EMAIL, PAT_TYPE, PAT_ASSIGNED_DOC, PAT_AILMENT, PAT_DISCHARGE_STATUS, PAT_GENDER, PAT_BLOOD_GROUP, PAT_EMERGENCY_CONTACT) VALUES
('PAT-DEMO-001', 'Eleanor', 'Vance', TO_DATE('1982-08-20', 'YYYY-MM-DD'), 42, '184 Pinecrest Avenue, Springfield, IL 62702', '+1 (555) 712-4401', 'eleanor.vance@curewell-demo.com', 'OutPatient', 'DOC-DEMO', 'Type 2 Diabetes Mellitus with Neuropathy', 'Active', 'Female', 'A+', 'Thomas Vance (Brother) - +1 (555) 712-4499');
INSERT INTO HIS_PATIENTS (PAT_NUMBER, PAT_FNAME, PAT_LNAME, PAT_DOB, PAT_AGE, PAT_ADDR, PAT_PHONE, PAT_EMAIL, PAT_TYPE, PAT_ASSIGNED_DOC, PAT_AILMENT, PAT_DISCHARGE_STATUS, PAT_GENDER, PAT_BLOOD_GROUP, PAT_EMERGENCY_CONTACT) VALUES
('PAT-DEMO-002', 'Marcus', 'Sterling', TO_DATE('1966-11-14', 'YYYY-MM-DD'), 58, '502 Harbor View Blvd, Chicago, IL 60601', '+1 (555) 712-4402', 'marcus.sterling@curewell-demo.com', 'InPatient', 'DOC-DEMO', 'Post-CABG Cardiac Recovery & Hypertension', 'Active', 'Male', 'B+', 'Clara Sterling (Wife) - +1 (555) 712-4498');
INSERT INTO HIS_PATIENTS (PAT_NUMBER, PAT_FNAME, PAT_LNAME, PAT_DOB, PAT_AGE, PAT_ADDR, PAT_PHONE, PAT_EMAIL, PAT_TYPE, PAT_ASSIGNED_DOC, PAT_AILMENT, PAT_DISCHARGE_STATUS, PAT_GENDER, PAT_BLOOD_GROUP, PAT_EMERGENCY_CONTACT) VALUES
('PAT-DEMO-003', 'Sophia', 'Chen', TO_DATE('1995-03-28', 'YYYY-MM-DD'), 29, '917 Willow Creek Way, Peoria, IL 61614', '+1 (555) 712-4403', 'sophia.chen@curewell-demo.com', 'OutPatient', 'DOC-DEMO', 'Acute Bronchial Asthma Exacerbation', 'Active', 'Female', 'AB-', 'David Chen (Father) - +1 (555) 712-4497');
INSERT INTO HIS_PATIENTS (PAT_NUMBER, PAT_FNAME, PAT_LNAME, PAT_DOB, PAT_AGE, PAT_ADDR, PAT_PHONE, PAT_EMAIL, PAT_TYPE, PAT_ASSIGNED_DOC, PAT_AILMENT, PAT_DISCHARGE_STATUS, PAT_GENDER, PAT_BLOOD_GROUP, PAT_EMERGENCY_CONTACT) VALUES
('PAT-DEMO-004', 'James', 'Holloway', TO_DATE('1959-07-04', 'YYYY-MM-DD'), 65, '330 Elmwood Lane, Rockford, IL 61108', '+1 (555) 712-4404', 'james.holloway@curewell-demo.com', 'InPatient', 'DOC-DEMO', 'Chronic Kidney Disease Stage 3', 'Active', 'Male', 'O-', 'Karen Holloway (Daughter) - +1 (555) 712-4496');
INSERT INTO HIS_PATIENTS (PAT_NUMBER, PAT_FNAME, PAT_LNAME, PAT_DOB, PAT_AGE, PAT_ADDR, PAT_PHONE, PAT_EMAIL, PAT_TYPE, PAT_ASSIGNED_DOC, PAT_AILMENT, PAT_DISCHARGE_STATUS, PAT_GENDER, PAT_BLOOD_GROUP, PAT_EMERGENCY_CONTACT) VALUES
('PAT-DEMO-005', 'Aaliyah', 'Patel', TO_DATE('1986-09-12', 'YYYY-MM-DD'), 38, '412 North Michigan Ave, Chicago, IL 60611', '+1 (555) 712-4405', 'aaliyah.patel@curewell-demo.com', 'OutPatient', 'DOC-DEMO', 'Refractory Migraine with Visual Aura', 'Active', 'Female', 'A-', 'Rohan Patel (Spouse) - +1 (555) 712-4495');

-- Pharmaceutical Categories
INSERT INTO HIS_PHARMACEUTICALS_CATEGORIES (PHARM_CAT_NAME, PHARM_CAT_VENDOR, PHARM_CAT_DESC) VALUES ('Antibiotics', 'PharmaCare International', 'Broad and narrow spectrum antibacterial agents');
INSERT INTO HIS_PHARMACEUTICALS_CATEGORIES (PHARM_CAT_NAME, PHARM_CAT_VENDOR, PHARM_CAT_DESC) VALUES ('Cardiovascular', 'CardioMed Devices', 'Beta blockers, ACE inhibitors, and antiarrhythmics');
INSERT INTO HIS_PHARMACEUTICALS_CATEGORIES (PHARM_CAT_NAME, PHARM_CAT_VENDOR, PHARM_CAT_DESC) VALUES ('Analgesics', 'MediSupply Corp', 'Non-opioid and opioid pain management formulations');
INSERT INTO HIS_PHARMACEUTICALS_CATEGORIES (PHARM_CAT_NAME, PHARM_CAT_VENDOR, PHARM_CAT_DESC) VALUES ('Endocrine & Metabolic', 'PharmaCare International', 'Insulin regimens and oral glycemic regulators');

-- Pharmaceuticals
INSERT INTO HIS_PHARMACEUTICALS (PHAR_NAME, PHAR_BCODE, PHAR_DESC, PHAR_QTY, PHAR_UNIT_PRICE, PHAR_CAT, PHAR_VENDOR, PHAR_EXPIRY_DATE, PHAR_MANUFACTURING_DATE) VALUES
('Atorvastatin 20mg', 'MED-BC-101', 'HMG-CoA reductase inhibitor for lipid management', 450, 14.50, 'Cardiovascular', 'PharmaCare International', TO_DATE('2027-12-31', 'YYYY-MM-DD'), TO_DATE('2024-01-15', 'YYYY-MM-DD'));
INSERT INTO HIS_PHARMACEUTICALS (PHAR_NAME, PHAR_BCODE, PHAR_DESC, PHAR_QTY, PHAR_UNIT_PRICE, PHAR_CAT, PHAR_VENDOR, PHAR_EXPIRY_DATE, PHAR_MANUFACTURING_DATE) VALUES
('Metoprolol Succinate 50mg', 'MED-BC-102', 'Extended-release cardioselective beta blocker', 600, 18.25, 'Cardiovascular', 'CardioMed Devices', TO_DATE('2027-08-15', 'YYYY-MM-DD'), TO_DATE('2024-03-10', 'YYYY-MM-DD'));
INSERT INTO HIS_PHARMACEUTICALS (PHAR_NAME, PHAR_BCODE, PHAR_DESC, PHAR_QTY, PHAR_UNIT_PRICE, PHAR_CAT, PHAR_VENDOR, PHAR_EXPIRY_DATE, PHAR_MANUFACTURING_DATE) VALUES
('Amoxicillin Clavulanate 875mg', 'MED-BC-103', 'Potentiated penicillin antibiotic', 320, 22.00, 'Antibiotics', 'PharmaCare International', TO_DATE('2026-11-30', 'YYYY-MM-DD'), TO_DATE('2024-05-01', 'YYYY-MM-DD'));
INSERT INTO HIS_PHARMACEUTICALS (PHAR_NAME, PHAR_BCODE, PHAR_DESC, PHAR_QTY, PHAR_UNIT_PRICE, PHAR_CAT, PHAR_VENDOR, PHAR_EXPIRY_DATE, PHAR_MANUFACTURING_DATE) VALUES
('Metformin HCl 1000mg ER', 'MED-BC-104', 'Biguanide antihyperglycemic oral agent', 850, 11.00, 'Endocrine & Metabolic', 'PharmaCare International', TO_DATE('2028-04-30', 'YYYY-MM-DD'), TO_DATE('2024-02-20', 'YYYY-MM-DD'));

-- Accounts
INSERT INTO HIS_ACCOUNTS (ACC_NAME, ACC_DESC, ACC_TYPE, ACC_NUMBER, ACC_AMOUNT, ACC_CURRENCY) VALUES ('Primary Clinical Operating Account', 'General hospital operations and disbursement', 'Asset Account', 'ACC-1001-01', 1250000.00, 'USD');
INSERT INTO HIS_ACCOUNTS (ACC_NAME, ACC_DESC, ACC_TYPE, ACC_NUMBER, ACC_AMOUNT, ACC_CURRENCY) VALUES ('Pharmacy Revenue Account', 'Prescription fulfillment and dispensary intake', 'Receivable Account', 'ACC-2002-02', 385400.00, 'USD');
INSERT INTO HIS_ACCOUNTS (ACC_NAME, ACC_DESC, ACC_TYPE, ACC_NUMBER, ACC_AMOUNT, ACC_CURRENCY) VALUES ('Biomedical Equipment CapEx', 'Capital expenditure and diagnostic hardware leases', 'Asset Account', 'ACC-3003-03', 750000.00, 'USD');

-- Assets
INSERT INTO HIS_ASSETS (ASST_NAME, ASST_DESC, ASST_VENDOR, ASST_STATUS, ASST_DEPT, ASST_PURCHASE_DATE, ASST_PURCHASE_COST, ASST_SERIAL_NUMBER) VALUES
('Siemens Magnetom 3T MRI Scanner', 'High-field superconducting whole-body MRI system', 'HealthTech Solutions', 'Active', 'Radiology & Imaging', TO_DATE('2023-06-15', 'YYYY-MM-DD'), 1450000.00, 'SN-MRI-3T-8821');
INSERT INTO HIS_ASSETS (ASST_NAME, ASST_DESC, ASST_VENDOR, ASST_STATUS, ASST_DEPT, ASST_PURCHASE_DATE, ASST_PURCHASE_COST, ASST_SERIAL_NUMBER) VALUES
('GE Healthcare Voluson E10 Ultrasound', 'Advanced 4D diagnostic ultrasound workstation', 'Global Medical Supplies', 'Active', 'Obstetrics & Cardiology', TO_DATE('2023-11-20', 'YYYY-MM-DD'), 185000.00, 'SN-US-VOL-4491');

-- Equipment
INSERT INTO HIS_EQUIPMENTS (EQP_CODE, EQP_NAME, EQP_VENDOR, EQP_DESC, EQP_DEPT, EQP_STATUS, EQP_QTY, EQP_LOCATION) VALUES
('EQP-001', 'Philips IntelliVue MX800 Patient Monitor', 'CardioMed Devices', 'Continuous ICU multi-parameter vital signs monitor', 'Cardiology ICU', 'Functioning', 24, 'Building A, 4th Floor ICU');
INSERT INTO HIS_EQUIPMENTS (EQP_CODE, EQP_NAME, EQP_VENDOR, EQP_DESC, EQP_DEPT, EQP_STATUS, EQP_QTY, EQP_LOCATION) VALUES
('EQP-002', 'Medtronic PB980 Ventilator', 'HealthTech Solutions', 'Advanced servo-controlled mechanical ventilator', 'Critical Care', 'Functioning', 16, 'Building B, 3rd Floor');

-- Laboratory Tests (Rich Clinical Seed)
INSERT INTO HIS_LABORATORY (LAB_NUMBER, LAB_PAT_NUMBER, LAB_DOC_NUMBER, LAB_PAT_TESTS, LAB_PAT_RESULTS, LAB_STATUS, LAB_DATE_REC, LAB_COMPLETED_DATE) VALUES
('LAB-1001', 'PAT-DEMO', 'DOC-DEMO', 'Comprehensive Metabolic Panel (CMP) + High-Sensitivity Troponin I', 'Troponin I: <0.01 ng/mL (Normal baseline). Na: 140 mEq/L, K: 4.2 mEq/L, Creatinine: 0.95 mg/dL. Renal function intact.', 'Completed', SYSTIMESTAMP - 4, SYSTIMESTAMP - 3);
INSERT INTO HIS_LABORATORY (LAB_NUMBER, LAB_PAT_NUMBER, LAB_DOC_NUMBER, LAB_PAT_TESTS, LAB_PAT_RESULTS, LAB_STATUS, LAB_DATE_REC, LAB_COMPLETED_DATE) VALUES
('LAB-1002', 'PAT-DEMO', 'DOC-DEMO', '12-Lead Electrocardiogram (ECG) & Transthoracic Echocardiogram', 'Sinus rhythm with mild LVH. LVEF estimated at 60%. Normal diastolic filling pattern. No acute ischemic ST-segment shifts.', 'Completed', SYSTIMESTAMP - 2, SYSTIMESTAMP - 1);
INSERT INTO HIS_LABORATORY (LAB_NUMBER, LAB_PAT_NUMBER, LAB_DOC_NUMBER, LAB_PAT_TESTS, LAB_PAT_RESULTS, LAB_STATUS, LAB_DATE_REC) VALUES
('LAB-1003', 'PAT-DEMO', 'DOC-DEMO', 'Fractional Excretion of Sodium & 24h Urine Microalbumin', 'Specimen received in pathology. Analysis queued on Beckman Coulter analyzer.', 'In Progress', SYSTIMESTAMP - 0.5);

-- Medical Records
INSERT INTO HIS_MEDICAL_RECORDS (MDR_NUMBER, MDR_PAT_NUMBER, MDR_DOC_NUMBER, MDR_PAT_PRESCR, MDR_DIAGNOSIS, MDR_TREATMENT_PLAN, MDR_DATE_REC) VALUES
('MDR-1001', 'PAT-DEMO', 'DOC-DEMO', 'Metoprolol Succinate 50mg PO Daily, Atorvastatin 20mg PO QHS', 'Stage 2 Essential Hypertension with exertional angina pectoris (CCS Class II)', 'Optimize oral antihypertensive therapy. Sodium restriction <2g/day. Scheduled cardiac stress imaging follow-up.', SYSTIMESTAMP - 10);
INSERT INTO HIS_MEDICAL_RECORDS (MDR_NUMBER, MDR_PAT_NUMBER, MDR_DOC_NUMBER, MDR_PAT_PRESCR, MDR_DIAGNOSIS, MDR_TREATMENT_PLAN, MDR_DATE_REC) VALUES
('MDR-1002', 'PAT-DEMO-002', 'DOC-DEMO', 'Aspirin 81mg PO Daily, Clopidogrel 75mg PO Daily', 'Post-Coronary Artery Bypass Graft (CABG x3) convalescence', 'Cardiac rehabilitation phase II. Continuous telemetry monitoring. Wound inspection every 48h.', SYSTIMESTAMP - 6);

-- Patient Transfers
INSERT INTO HIS_PATIENT_TRANSFER (PT_PAT_NUMBER, PT_FROM_WARD, PT_TO_WARD, PT_REASON, PT_AUTHORIZED_BY, PT_STATUS) VALUES
('PAT-DEMO', 'Emergency Resuscitation Bay 3', 'Cardiology Intermediate Care (Ward 4B)', 'Hemodynamic stabilization following acute angina presentation', 'DOC-DEMO', 'Completed');

-- Payrolls
INSERT INTO HIS_PAYROLLS (PAY_NUMBER, PAY_DOC_NUMBER, PAY_AMOUNT, PAY_PERIOD, PAY_STATUS, PAY_DATE, PAY_METHOD) VALUES
('PAY-1001', 'DOC-DEMO', 18500.00, 'September 2026', 'Paid', TO_DATE('2026-09-01', 'YYYY-MM-DD'), 'Direct Deposit');
INSERT INTO HIS_PAYROLLS (PAY_NUMBER, PAY_DOC_NUMBER, PAY_AMOUNT, PAY_PERIOD, PAY_STATUS, PAY_DATE, PAY_METHOD) VALUES
('PAY-1002', 'DOC001', 16200.00, 'September 2026', 'Paid', TO_DATE('2026-09-01', 'YYYY-MM-DD'), 'Direct Deposit');

-- Prescriptions
INSERT INTO HIS_PRESCRIPTIONS (PRES_NUMBER, PRES_PAT_NUMBER, PRES_DOC_NUMBER, PRES_MEDICATION, PRES_DOSAGE, PRES_FREQUENCY, PRES_DURATION, PRES_STATUS, PRES_REFILLS_REMAINING, PRES_NOTES) VALUES
('PRES-1001', 'PAT-DEMO', 'DOC-DEMO', 'Metoprolol Succinate Extended-Release', '50 mg', 'Once daily in the morning', '90 days', 'Active', 3, 'Take with meals. Monitor resting pulse prior to administration.');
INSERT INTO HIS_PRESCRIPTIONS (PRES_NUMBER, PRES_PAT_NUMBER, PRES_DOC_NUMBER, PRES_MEDICATION, PRES_DOSAGE, PRES_FREQUENCY, PRES_DURATION, PRES_STATUS, PRES_REFILLS_REMAINING, PRES_NOTES) VALUES
('PRES-1002', 'PAT-DEMO', 'DOC-DEMO', 'Atorvastatin Calcium', '20 mg', 'Once daily at bedtime', '90 days', 'Active', 3, 'Target LDL < 70 mg/dL. Routine hepatic panel in 12 weeks.');
INSERT INTO HIS_PRESCRIPTIONS (PRES_NUMBER, PRES_PAT_NUMBER, PRES_DOC_NUMBER, PRES_MEDICATION, PRES_DOSAGE, PRES_FREQUENCY, PRES_DURATION, PRES_STATUS, PRES_REFILLS_REMAINING, PRES_NOTES) VALUES
('PRES-1003', 'PAT-DEMO', 'DOC-DEMO', 'Nitroglycerin Sublingual Tablets', '0.4 mg', 'As needed for acute chest tightness', 'PRN (30 days)', 'Active', 2, 'Dissolve 1 tablet sublingually every 5 min up to 3 doses if angina occurs.');

-- Surgeries
INSERT INTO HIS_SURGERY (SURG_NUMBER, SURG_PAT_NUMBER, SURG_DOC_NUMBER, SURG_TYPE, SURG_DATE, SURG_DURATION, SURG_STATUS, SURG_NOTES) VALUES
('SURG-1001', 'PAT-DEMO', 'DOC-DEMO', 'Diagnostic Coronary Angiography & Fractional Flow Reserve', SYSTIMESTAMP + 5, '1.5 hours', 'Scheduled', 'Right radial artery access planned. Patient consented for hemodynamic pressure wire assessment.');

-- Vitals
INSERT INTO HIS_VITALS (VIT_PAT_NUMBER, VIT_BODYTEMP, VIT_HEARTPULSE, VIT_RESPIRATION, VIT_WEIGHT, VIT_BLOOD_PRESSURE, VIT_OXYGEN_SAT, VIT_RECORDED_BY, VIT_RECORDED_DATE) VALUES
('PAT-DEMO', 98.4, 72, 16, 78.5, '124/82', 98.5, 'Nurse Practitioner J. Kelly', SYSTIMESTAMP - 0.2);
INSERT INTO HIS_VITALS (VIT_PAT_NUMBER, VIT_BODYTEMP, VIT_HEARTPULSE, VIT_RESPIRATION, VIT_WEIGHT, VIT_BLOOD_PRESSURE, VIT_OXYGEN_SAT, VIT_RECORDED_BY, VIT_RECORDED_DATE) VALUES
('PAT-DEMO', 98.6, 76, 17, 78.8, '132/86', 99.0, 'Nurse Practitioner J. Kelly', SYSTIMESTAMP - 1.0);
INSERT INTO HIS_VITALS (VIT_PAT_NUMBER, VIT_BODYTEMP, VIT_HEARTPULSE, VIT_RESPIRATION, VIT_WEIGHT, VIT_BLOOD_PRESSURE, VIT_OXYGEN_SAT, VIT_RECORDED_BY, VIT_RECORDED_DATE) VALUES
('PAT-DEMO', 99.1, 84, 18, 79.1, '142/90', 97.8, 'Triage RN R. Miller', SYSTIMESTAMP - 2.5);

COMMIT;

-- =====================================================
-- SECTION 7: FINAL INTEGRITY VERIFICATION REPORT
-- =====================================================

SELECT '============================================' AS REPORT FROM DUAL;
SELECT 'CUREWELL HMS: MASTER DATABASE DEPLOYMENT STATUS' AS REPORT FROM DUAL;
SELECT '============================================' AS REPORT FROM DUAL;

SELECT 'Tables Created: ' || COUNT(*) AS SUMMARY FROM user_tables WHERE table_name LIKE 'HIS_%';
SELECT 'Sequences Created: ' || COUNT(*) AS SUMMARY FROM user_sequences WHERE sequence_name LIKE 'HIS_%';
SELECT 'Views Created: ' || COUNT(*) AS SUMMARY FROM user_views WHERE view_name LIKE 'V_%';
SELECT 'Foreign Keys Active: ' || COUNT(*) AS SUMMARY FROM user_constraints WHERE constraint_type = 'R' AND table_name LIKE 'HIS_%';
SELECT 'Triggers Active: ' || COUNT(*) AS SUMMARY FROM user_triggers WHERE trigger_name LIKE 'HIS_%';

SELECT 'Demo Accounts Available for Login:' AS SUMMARY FROM DUAL;
SELECT '  - Admin   : admin@curewell.com / admin' AS SUMMARY FROM DUAL;
SELECT '  - Doctor  : doctor@curewell.com / doctor (DOC-DEMO: Dr. Alexander Hayes)' AS SUMMARY FROM DUAL;
SELECT '  - Patient : demo.patient@curewell.com / patient (PAT-DEMO: Alex Morgan)' AS SUMMARY FROM DUAL;
